@extends('layouts.admin')
@section('title', 'Daily Stock Closing')
@section('content')
<div class="py-6 max-w-7xl mx-auto px-4 space-y-5">
 @if(session('success'))<div class="bg-green-100 text-green-800 p-4 rounded">{{ session('success') }}</div>@endif
 <div class="bg-white rounded shadow p-5"><h2 class="text-2xl font-bold">Daily Stock — {{ $dailyStock->business->name }}</h2><p class="text-gray-600">{{ $dailyStock->closing_date->format('d/m/Y') }} · Recorded by {{ $dailyStock->recorder->name }}</p></div>
 <div class="grid md:grid-cols-3 gap-4">@foreach(['Revenue'=>$dailyStock->items->sum('revenue'),'COGS'=>$dailyStock->items->sum('cost_of_goods_sold'),'Gross Profit'=>$dailyStock->items->sum('gross_profit')] as $label=>$value)<div class="bg-white rounded shadow p-4"><small class="text-gray-500">{{ $label }}</small><strong class="block text-xl">TZS {{ number_format($value,2) }}</strong></div>@endforeach</div>
 <div class="bg-white rounded shadow overflow-x-auto"><table class="w-full min-w-[1050px] text-left"><thead class="bg-gray-100"><tr><th class="p-3">Product</th><th>Opening</th><th>Received</th><th>Available</th><th>Closing</th><th>Sold</th><th>Sell Price</th><th>Avg Cost</th><th>Revenue</th><th>Profit</th></tr></thead><tbody>@foreach($dailyStock->items as $item)<tr class="border-t"><td class="p-3">{{ $item->product->name }}</td><td>{{ $item->opening_units }}</td><td>{{ $item->received_units }}</td><td>{{ $item->available_units }}</td><td>{{ $item->closing_units }}</td><td>{{ $item->sold_units }}</td><td>{{ number_format($item->selling_price,2) }}</td><td>{{ number_format($item->average_cost_per_unit,2) }}</td><td>{{ number_format($item->revenue,2) }}</td><td>{{ number_format($item->gross_profit,2) }}</td></tr>@endforeach</tbody></table></div>
 @if($dailyStock->autoRequest)<div class="bg-white rounded shadow p-5"><h3 class="font-bold text-lg">Automatic Stock Request</h3><p class="mb-3">{{ $dailyStock->autoRequest->request_number }} — {{ ucwords($dailyStock->autoRequest->status) }}</p><div class="divide-y border rounded">@foreach($dailyStock->autoRequest->items as $item)<div class="p-3 flex justify-between"><span>{{ $item->product->name }}</span><strong>{{ $item->requested_packages }} packages</strong></div>@endforeach</div>@if($dailyStock->autoRequest->status==='draft')<form class="mt-4" method="POST" action="{{ route('procurement.requests.confirm-auto',$dailyStock->autoRequest) }}">@csrf<button class="bg-blue-600 text-white px-4 py-2 rounded">Confirm & Send Request</button></form>@endif<a class="inline-block mt-4 text-blue-700" href="{{ route('procurement.requests.show',$dailyStock->autoRequest) }}">Open request</a></div>@endif
</div>
@endsection
