@extends('layouts.admin')
@section('title', 'Stock Request')
@section('content')
    <div class="py-6 max-w-6xl mx-auto px-4 space-y-6">
        @if(session('success'))<div class="bg-green-100 text-green-800 p-4 rounded">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="bg-red-100 text-red-800 p-4 rounded"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="bg-white shadow rounded p-5 flex flex-wrap gap-8"><div><small>Branch</small><b class="block">{{ $stockRequest->business->name }}</b></div><div><small>Date</small><b class="block">{{ $stockRequest->request_date->format('d/m/Y') }}</b></div><div><small>Requested By</small><b class="block">{{ $stockRequest->requester->name }}</b></div><div><small>Status</small><b class="block">{{ ucwords(str_replace('_',' ',$stockRequest->status)) }}</b></div></div>
        <div class="bg-white shadow rounded overflow-x-auto"><table class="w-full"><thead class="bg-gray-100"><tr><th class="p-3 text-left">Product</th><th>Requested Packages</th><th>Approved</th><th>Units/Package</th></tr></thead><tbody>@foreach($stockRequest->items as $item)<tr class="border-t"><td class="p-3">{{ $item->product->name }}</td><td class="text-center">{{ $item->requested_packages }}</td><td class="text-center">{{ $item->approved_packages ?? '-' }}</td><td class="text-center">{{ $item->units_per_package }}</td></tr>@endforeach</tbody></table></div>
        @if($stockRequest->status==='pending' && in_array(auth()->user()->role?->name,['admin','manager']))
        <form method="POST" action="{{ route('procurement.requests.review',$stockRequest) }}" class="bg-white shadow rounded p-5">@csrf<h3 class="font-bold mb-3">Review Request</h3>@foreach($stockRequest->items as $item)<label class="block mb-2">{{ $item->product->name }} approved packages<input name="approved[{{ $item->id }}]" type="number" step="0.01" min="0" max="{{ $item->requested_packages }}" value="{{ $item->requested_packages }}" class="border rounded p-2 ml-2"></label>@endforeach<textarea name="review_notes" placeholder="Review notes" class="w-full border rounded p-2 my-3"></textarea><button name="decision" value="approved" class="bg-green-600 text-white px-4 py-2 rounded">Approve</button><button name="decision" value="rejected" class="bg-red-600 text-white px-4 py-2 rounded">Reject</button></form>
        @endif
        @if($stockRequest->status==='approved' && in_array(auth()->user()->role?->name,['admin','manager']))
        <form method="POST" action="{{ route('procurement.requests.order',$stockRequest) }}" class="bg-white shadow rounded p-5">@csrf<h3 class="font-bold mb-3">Create Purchase Order</h3><input name="order_date" type="date" value="{{ date('Y-m-d') }}" class="border rounded p-2 mb-3" required><input name="supplier" placeholder="Supplier" class="border rounded p-2 mb-3">@foreach($stockRequest->items->where('approved_packages','>',0) as $item)<label class="block mb-2">{{ $item->product->name }} cost per package<input name="costs[{{ $item->id }}]" type="number" step="0.01" min="0" class="border rounded p-2 ml-2" required></label>@endforeach<textarea name="notes" placeholder="Order notes" class="w-full border rounded p-2 my-3"></textarea><button class="bg-blue-600 text-white px-4 py-2 rounded">Create Order</button></form>
        @endif
        @if($stockRequest->purchaseOrder)
        @php($order=$stockRequest->purchaseOrder)
        <div class="bg-white shadow rounded p-5"><h3 class="font-bold">Order {{ $order->order_number }} — {{ ucwords(str_replace('_',' ',$order->status)) }}</h3></div>
        @if(in_array($order->status,['ordered','partially_received']))
        <form method="POST" action="{{ route('procurement.orders.receive',$order) }}" class="bg-white shadow rounded p-5">@csrf<h3 class="font-bold mb-3">Confirm Goods Received</h3><input name="receipt_date" type="date" value="{{ date('Y-m-d') }}" class="border rounded p-2 mb-3" required>@foreach($order->items as $item)@php($remaining=(float)$item->ordered_packages-(float)$item->receiptItems->sum('received_packages'))<label class="block mb-2">{{ $item->product->name }} (remaining {{ $remaining }})<input name="received[{{ $item->id }}]" type="number" step="0.01" min="0" max="{{ $remaining }}" value="{{ $remaining }}" class="border rounded p-2 ml-2"></label>@endforeach<textarea name="notes" placeholder="Receipt notes / discrepancy reason" class="w-full border rounded p-2 my-3"></textarea><button class="bg-green-600 text-white px-4 py-2 rounded">Confirm Receipt</button></form>
        @endif @endif
    </div>
@endsection
