@extends('layouts.admin')
@section('title', 'Stock Request')
@section('content')
    <div class="py-6 max-w-6xl mx-auto px-4 space-y-6">
        @if(session('success'))<div class="bg-green-100 text-green-800 p-4 rounded">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="bg-red-100 text-red-800 p-4 rounded"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <div class="bg-white shadow rounded p-5 flex flex-wrap gap-8"><div><small>Branch</small><b class="block">{{ $stockRequest->business->name }}</b></div><div><small>Date</small><b class="block">{{ $stockRequest->request_date->format('d/m/Y') }}</b></div><div><small>Requested By</small><b class="block">{{ $stockRequest->requester->name }}</b></div><div><small>Status</small><b class="block">{{ ucwords(str_replace('_',' ',$stockRequest->status)) }}</b></div></div>
        <div class="bg-white shadow rounded overflow-x-auto"><table class="w-full"><thead class="bg-gray-100"><tr><th class="p-3 text-left">Product</th><th>Requested Packages</th><th>Approved</th><th>Units/Package</th></tr></thead><tbody>@foreach($stockRequest->items as $item)<tr class="border-t"><td class="p-3">{{ $item->product->name }}</td><td class="text-center">{{ $item->requested_packages }}</td><td class="text-center">{{ $item->approved_packages ?? '-' }}</td><td class="text-center">{{ $item->units_per_package }}</td></tr>@endforeach</tbody></table></div>
        @if($stockRequest->status==='pending' && in_array(auth()->user()->role?->name,['admin','manager']))
        <div class="bg-white shadow rounded p-5"><h3 class="font-bold mb-2">Review Request</h3><p class="text-gray-600 mb-4">Review requested products step by step.</p><button type="button" id="open-review-wizard" class="bg-blue-600 text-white px-4 py-2 rounded">Start Review</button></div>
        <div id="review-wizard" class="hidden fixed inset-0 z-50 bg-black/50 p-4 overflow-y-auto"><div class="bg-white rounded-xl shadow-xl max-w-2xl mx-auto my-8 p-6"><div class="flex justify-between items-center mb-5"><div><h3 class="font-bold text-xl">Review Stock Request</h3><p id="review-progress" class="text-sm text-gray-500"></p></div><button type="button" id="close-review-wizard" class="text-2xl text-gray-500">&times;</button></div><form id="review-form" method="POST" action="{{ route('procurement.requests.review',$stockRequest) }}">@csrf
            @foreach($stockRequest->items->values() as $index=>$item)<section class="review-step {{ $index ? 'hidden' : '' }}"><div class="bg-gray-50 border rounded p-4 mb-4"><span class="text-gray-500 text-sm">Product</span><h4 class="font-bold text-lg">{{ $item->product->name }}</h4><p>Requested: {{ number_format($item->requested_packages,2) }} packages</p></div><label class="block mb-1">Approved Packages *</label><input class="review-quantity w-full border rounded p-3" data-product="{{ $item->product->name }}" data-requested="{{ $item->requested_packages }}" name="approved[{{ $item->id }}]" type="number" step="0.01" min="0" max="{{ $item->requested_packages }}" value="{{ $item->requested_packages }}" required></section>@endforeach
            <section class="review-step hidden"><h4 class="font-bold text-lg mb-3">Review Summary</h4><div id="review-summary" class="border rounded divide-y max-h-[50vh] overflow-y-auto mb-4"></div><label class="block mb-1">Review Notes</label><textarea name="review_notes" placeholder="Required when rejecting" class="w-full border rounded p-2"></textarea></section>
            <div class="flex justify-between mt-6"><button type="button" id="review-previous" class="hidden bg-gray-200 px-4 py-2 rounded">Previous</button><div class="ml-auto flex gap-2"><button type="button" id="review-next" class="bg-blue-600 text-white px-4 py-2 rounded">Next</button><button name="decision" value="rejected" id="review-reject" class="hidden bg-red-600 text-white px-4 py-2 rounded">Reject Request</button><button name="decision" value="approved" id="review-approve" class="hidden bg-green-600 text-white px-4 py-2 rounded">Approve Request</button></div></div>
        </form></div></div>
        <script>(()=>{const modal=document.getElementById('review-wizard'),steps=[...document.querySelectorAll('.review-step')],progress=document.getElementById('review-progress'),previous=document.getElementById('review-previous'),next=document.getElementById('review-next'),approve=document.getElementById('review-approve'),reject=document.getElementById('review-reject');let current=0;function summary(){const box=document.getElementById('review-summary');box.innerHTML='';document.querySelectorAll('.review-quantity').forEach(input=>{const row=document.createElement('div'),name=document.createElement('span'),amount=document.createElement('strong');row.className='p-3 flex justify-between gap-3';name.textContent=input.dataset.product;amount.textContent=`${input.value} / ${input.dataset.requested} packages`;row.append(name,amount);box.appendChild(row)})}function show(){steps.forEach((step,index)=>step.classList.toggle('hidden',index!==current));progress.textContent=current<steps.length-1?`Product ${current+1} of ${steps.length-1}`:'Final summary';previous.classList.toggle('hidden',current===0);next.classList.toggle('hidden',current===steps.length-1);approve.classList.toggle('hidden',current!==steps.length-1);reject.classList.toggle('hidden',current!==steps.length-1);if(current===steps.length-1)summary()}function valid(){const input=steps[current].querySelector('input');if(input&&!input.checkValidity()){input.reportValidity();return false}return true}document.getElementById('open-review-wizard').onclick=()=>{modal.classList.remove('hidden');current=0;show()};document.getElementById('close-review-wizard').onclick=()=>modal.classList.add('hidden');next.onclick=()=>{if(valid()){current++;show()}};previous.onclick=()=>{current--;show()};modal.addEventListener('click',event=>{if(event.target===modal)modal.classList.add('hidden')})})();</script>
        @endif
        @if($stockRequest->status==='approved' && in_array(auth()->user()->role?->name,['admin','manager']))
        @php($approvedItems=$stockRequest->items->where('approved_packages','>',0)->values())
        <div class="bg-white shadow rounded p-5">
            <h3 class="font-bold mb-2">Create Purchase Order</h3>
            <p class="text-gray-600 mb-4">Supplier, payment details and package prices will be completed step by step.</p>
            <button type="button" id="open-order-wizard" class="bg-blue-600 text-white px-4 py-2 rounded">Start Purchase Order</button>
        </div>

        <div id="order-wizard" class="hidden fixed inset-0 z-50 bg-black/50 p-4 overflow-y-auto">
            <div class="bg-white rounded-xl shadow-xl max-w-2xl mx-auto my-8 p-6">
                <div class="flex justify-between items-center mb-5"><div><h3 class="font-bold text-xl">Create Purchase Order</h3><p id="wizard-progress" class="text-sm text-gray-500"></p></div><button type="button" id="close-order-wizard" class="text-2xl text-gray-500">&times;</button></div>
                <form id="purchase-order-form" method="POST" action="{{ route('procurement.requests.order',$stockRequest) }}">@csrf
                    <section class="wizard-step" data-step="0">
                        <label class="block mb-1">Order Date *</label><input name="order_date" type="date" value="{{ date('Y-m-d') }}" max="{{ date('Y-m-d') }}" class="w-full border rounded p-2 mb-3" required>
                        <label class="block mb-1">Supplier *</label><select name="supplier_id" class="w-full border rounded p-2 mb-3"><option value="">Select supplier (required for credit)</option>@foreach($suppliers as $supplier)<option value="{{ $supplier->id }}">{{ $supplier->name }}</option>@endforeach</select>
                        <label class="block mb-1">Payment Type *</label><select id="wizard-payment-type" name="payment_type" class="w-full border rounded p-2 mb-3" required><option value="credit">Supplier Credit</option><option value="cash">Cash / Paid Now</option></select>
                        <div id="wizard-account-wrap" class="hidden"><label class="block mb-1">Payment Account *</label><select id="wizard-account" name="payment_financial_account_id" class="w-full border rounded p-2 mb-3"><option value="">Select payment account</option>@foreach($financialAccounts as $account)<option value="{{ $account->id }}">{{ $account->name }} — TZS {{ number_format($account->current_balance,2) }}</option>@endforeach</select></div>
                    </section>
                    @foreach($approvedItems as $index=>$item)
                    @php($defaultCost=(float)($lastPackageCosts[$item->product_id] ?? 0))
                    <section class="wizard-step hidden" data-step="{{ $index+1 }}">
                        <div class="bg-gray-50 border rounded p-4 mb-4"><span class="text-gray-500 text-sm">Product</span><h4 class="font-bold text-lg">{{ $item->product->name }}</h4><p>Approved: {{ number_format($item->approved_packages,2) }} packages</p></div>
                        <label class="block mb-1">Cost per package *</label><input class="wizard-cost w-full border rounded p-3" data-product="{{ $item->product->name }}" data-quantity="{{ $item->approved_packages }}" name="costs[{{ $item->id }}]" type="number" step="0.01" min="0.01" value="{{ $defaultCost > 0 ? $defaultCost : '' }}" required>
                        <p class="text-sm text-gray-500 mt-2">{{ $defaultCost > 0 ? 'Autofill from last/default purchase price: TZS '.number_format($defaultCost,2) : 'No previous price. Enter the current supplier price.' }}</p>
                    </section>
                    @endforeach
                    <section class="wizard-step hidden" data-step="{{ $approvedItems->count()+1 }}"><h4 class="font-bold text-lg mb-3">Order Summary</h4><div id="order-summary" class="border rounded divide-y mb-4"></div><div class="flex justify-between text-lg font-bold mb-4"><span>Grand Total</span><span id="order-grand-total">TZS 0.00</span></div><label class="block mb-1">Order Notes</label><textarea name="notes" placeholder="Optional notes" class="w-full border rounded p-2"></textarea></section>
                    <p id="wizard-error" class="hidden text-red-600 mt-3"></p>
                    <div class="flex justify-between mt-6"><button type="button" id="wizard-previous" class="hidden bg-gray-200 px-4 py-2 rounded">Previous</button><div class="ml-auto flex gap-2"><button type="button" id="wizard-next" class="bg-blue-600 text-white px-4 py-2 rounded">Next</button><button type="submit" id="wizard-submit" class="hidden bg-green-600 text-white px-4 py-2 rounded">Create Purchase Order</button></div></div>
                </form>
            </div>
        </div>
        <script>
            (() => {
                const modal=document.getElementById('order-wizard'), steps=[...document.querySelectorAll('.wizard-step')], progress=document.getElementById('wizard-progress'), error=document.getElementById('wizard-error'), previous=document.getElementById('wizard-previous'), next=document.getElementById('wizard-next'), submit=document.getElementById('wizard-submit'), paymentType=document.getElementById('wizard-payment-type'), accountWrap=document.getElementById('wizard-account-wrap'), account=document.getElementById('wizard-account'); let current=0;
                const money=value=>'TZS '+Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
                function paymentFields(){const cash=paymentType.value==='cash';accountWrap.classList.toggle('hidden',!cash);account.required=cash;if(!cash)account.value='';}
                function summary(){const box=document.getElementById('order-summary');box.innerHTML='';let total=0;document.querySelectorAll('.wizard-cost').forEach(input=>{const line=Number(input.value)*Number(input.dataset.quantity);total+=line;const row=document.createElement('div'),label=document.createElement('span'),amount=document.createElement('strong');row.className='p-3 flex justify-between gap-3';label.textContent=`${input.dataset.product} × ${input.dataset.quantity}`;amount.textContent=money(line);row.append(label,amount);box.appendChild(row)});document.getElementById('order-grand-total').textContent=money(total)}
                function show(){steps.forEach((step,index)=>step.classList.toggle('hidden',index!==current));progress.textContent=current===0?'Order details':current<=steps.length-2?`Product ${current} of ${steps.length-2}`:'Final summary';previous.classList.toggle('hidden',current===0);next.classList.toggle('hidden',current===steps.length-1);submit.classList.toggle('hidden',current!==steps.length-1);error.classList.add('hidden');if(current===steps.length-1)summary()}
                function valid(){const fields=[...steps[current].querySelectorAll('input,select')];for(const field of fields){if(!field.checkValidity()){field.reportValidity();return false}}if(current===0&&paymentType.value==='credit'&&!document.querySelector('[name="supplier_id"]').value){error.textContent='Chagua supplier kwa credit purchase.';error.classList.remove('hidden');return false}return true}
                document.getElementById('open-order-wizard').onclick=()=>{modal.classList.remove('hidden');current=0;paymentFields();show()};document.getElementById('close-order-wizard').onclick=()=>modal.classList.add('hidden');paymentType.onchange=paymentFields;next.onclick=()=>{if(valid()){current++;show()}};previous.onclick=()=>{current--;show()};modal.addEventListener('click',event=>{if(event.target===modal)modal.classList.add('hidden')});
            })();
        </script>
        @endif
        @if($stockRequest->purchaseOrder)
        @php($order=$stockRequest->purchaseOrder)
        <div class="bg-white shadow rounded p-5"><h3 class="font-bold">Order {{ $order->order_number }} — {{ ucwords(str_replace('_',' ',$order->status)) }}</h3></div>
        @if(in_array($order->status,['ordered','partially_received']))
        <div class="bg-white shadow rounded p-5"><h3 class="font-bold mb-2">Goods Receipt</h3><p class="text-gray-600 mb-4">Record the quantities actually received.</p><button type="button" id="open-receipt-wizard" class="bg-green-600 text-white px-4 py-2 rounded">Receive Goods</button></div>
        <div id="receipt-wizard" class="hidden fixed inset-0 z-50 bg-black/50 p-4 overflow-y-auto"><div class="bg-white rounded-xl shadow-xl max-w-2xl mx-auto my-8 p-6"><div class="flex justify-between items-center mb-5"><div><h3 class="font-bold text-xl">Confirm Goods Received</h3><p id="receipt-progress" class="text-sm text-gray-500"></p></div><button type="button" id="close-receipt-wizard" class="text-2xl text-gray-500">&times;</button></div><form method="POST" action="{{ route('procurement.orders.receive',$order) }}">@csrf
            <section class="receipt-step"><label class="block mb-1">Receipt Date *</label><input name="receipt_date" type="date" value="{{ date('Y-m-d') }}" max="{{ date('Y-m-d') }}" class="w-full border rounded p-3" required></section>
            @foreach($order->items->values() as $index=>$item)@php($already=(float)$item->receiptItems->sum('received_packages'))@php($remaining=(float)$item->ordered_packages-$already)<section class="receipt-step hidden"><div class="bg-gray-50 border rounded p-4 mb-4"><span class="text-gray-500 text-sm">Product</span><h4 class="font-bold text-lg">{{ $item->product->name }}</h4><p>Ordered: {{ number_format($item->ordered_packages,2) }} | Previously received: {{ number_format($already,2) }} | Remaining: {{ number_format($remaining,2) }}</p></div><label class="block mb-1">Packages Received Now *</label><input class="receipt-quantity w-full border rounded p-3" data-product="{{ $item->product->name }}" data-remaining="{{ $remaining }}" name="received[{{ $item->id }}]" type="number" step="0.01" min="0" max="{{ $remaining }}" value="{{ $remaining }}" required></section>@endforeach
            <section class="receipt-step hidden"><h4 class="font-bold text-lg mb-3">Receipt Summary</h4><div id="receipt-summary" class="border rounded divide-y max-h-[45vh] overflow-y-auto mb-4"></div><label class="block mb-1">Receipt Notes / Discrepancy Reason</label><textarea name="notes" class="w-full border rounded p-2"></textarea></section>
            <div class="flex justify-between mt-6"><button type="button" id="receipt-previous" class="hidden bg-gray-200 px-4 py-2 rounded">Previous</button><div class="ml-auto"><button type="button" id="receipt-next" class="bg-blue-600 text-white px-4 py-2 rounded">Next</button><button id="receipt-submit" class="hidden bg-green-600 text-white px-4 py-2 rounded">Confirm Receipt</button></div></div>
        </form></div></div>
        <script>(()=>{const modal=document.getElementById('receipt-wizard'),steps=[...document.querySelectorAll('.receipt-step')],progress=document.getElementById('receipt-progress'),previous=document.getElementById('receipt-previous'),next=document.getElementById('receipt-next'),submit=document.getElementById('receipt-submit');let current=0;function summary(){const box=document.getElementById('receipt-summary');box.innerHTML='';document.querySelectorAll('.receipt-quantity').forEach(input=>{const row=document.createElement('div'),name=document.createElement('span'),amount=document.createElement('strong');row.className='p-3 flex justify-between gap-3';name.textContent=input.dataset.product;amount.textContent=`${input.value} packages`;row.append(name,amount);box.appendChild(row)})}function show(){steps.forEach((step,index)=>step.classList.toggle('hidden',index!==current));progress.textContent=current===0?'Receipt details':current<steps.length-1?`Product ${current} of ${steps.length-2}`:'Final summary';previous.classList.toggle('hidden',current===0);next.classList.toggle('hidden',current===steps.length-1);submit.classList.toggle('hidden',current!==steps.length-1);if(current===steps.length-1)summary()}function valid(){const input=steps[current].querySelector('input');if(input&&!input.checkValidity()){input.reportValidity();return false}return true}document.getElementById('open-receipt-wizard').onclick=()=>{modal.classList.remove('hidden');current=0;show()};document.getElementById('close-receipt-wizard').onclick=()=>modal.classList.add('hidden');next.onclick=()=>{if(valid()){current++;show()}};previous.onclick=()=>{current--;show()};modal.addEventListener('click',event=>{if(event.target===modal)modal.classList.add('hidden')})})();</script>
        @endif @endif
    </div>
@endsection
