@extends('layouts.admin')
@section('title','Suppliers & Bills')
@section('content')
<div class="max-w-7xl mx-auto py-6 px-6">
@if(session('success'))<div class="bg-green-100 text-green-700 p-3 rounded mb-5">{{ session('success') }}</div>@endif
@if($errors->any())<div class="bg-red-100 text-red-700 p-3 rounded mb-5">{{ $errors->first() }}</div>@endif
<div class="grid xl:grid-cols-3 gap-6">
<form method="POST" action="{{ route('suppliers.store') }}" class="bg-white shadow rounded-xl p-5 h-fit">@csrf<h2 class="font-bold text-lg mb-4">Add Supplier</h2><input name="name" placeholder="Supplier name" required class="w-full border rounded p-2 mb-3"><input name="phone" placeholder="Phone" class="w-full border rounded p-2 mb-3"><input name="email" type="email" placeholder="Email" class="w-full border rounded p-2 mb-3"><textarea name="address" placeholder="Address" class="w-full border rounded p-2 mb-3"></textarea><button class="w-full bg-blue-600 text-white p-2 rounded">Save Supplier</button></form>
<div class="xl:col-span-2 space-y-6">
<div class="bg-white shadow rounded-xl overflow-x-auto"><table class="w-full"><thead class="bg-gray-100"><tr><th class="p-3 text-left">Supplier</th><th>Phone</th><th>Outstanding</th></tr></thead><tbody>@forelse($suppliers as $supplier)<tr class="border-t"><td class="p-3">{{ $supplier->name }}</td><td>{{ $supplier->phone ?? '-' }}</td><td>TZS {{ number_format($supplier->outstanding ?? 0,2) }}</td></tr>@empty<tr><td colspan="3" class="p-5 text-center">No suppliers.</td></tr>@endforelse</tbody></table></div>
<div class="bg-white shadow rounded-xl overflow-x-auto"><table class="w-full min-w-[1000px]"><thead class="bg-gray-100"><tr><th class="p-3 text-left">Bill</th><th>Supplier</th><th>Branch</th><th>Original</th><th>Balance</th><th>Status</th><th>Payment</th></tr></thead><tbody>@forelse($bills as $bill)<tr class="border-t"><td class="p-3">{{ $bill->bill_number }}</td><td>{{ $bill->supplier?->name ?? $bill->goodsReceipt->purchaseOrder->supplier ?? 'Cash supplier' }}</td><td>{{ $bill->business->name }}</td><td>TZS {{ number_format($bill->original_amount,2) }}</td><td>TZS {{ number_format($bill->balance,2) }}</td><td>{{ ucfirst($bill->status) }}</td><td>@if($bill->balance>0 && in_array(auth()->user()->role?->name,['admin','manager']))<form method="POST" action="{{ route('supplier-bills.pay',$bill) }}" class="flex gap-1">@csrf<select name="financial_account_id" required class="border rounded p-1"><option value="">Account</option>@foreach($financialAccounts as $account)<option value="{{ $account->id }}">{{ $account->name }}</option>@endforeach</select><input name="amount" type="number" step="0.01" max="{{ $bill->balance }}" value="{{ $bill->balance }}" class="border rounded p-1 w-28"><input name="payment_date" type="date" value="{{ date('Y-m-d') }}" class="border rounded p-1"><input type="hidden" name="payment_method" value="cash"><button class="bg-green-600 text-white px-2 rounded">Pay</button></form>@else - @endif</td></tr>@empty<tr><td colspan="7" class="p-6 text-center">No supplier bills.</td></tr>@endforelse</tbody></table><div class="p-3">{{ $bills->links() }}</div></div>
</div></div></div>
@endsection
